INSERT INTO burgers (burgerName) VALUES ("The Sound and the Curry Burger");
INSERT INTO burgers (burgerName) VALUES ("New Baconings Burger");
INSERT INTO burgers (burgerName) VALUES ("These Collards Don't Run Burger");
INSERT INTO burgers (burgerName) VALUES ("Don't You Four Cheddar 'Bout Me Burger (comes with four kinds of cheddar)");
INSERT INTO burgers (burgerName) VALUES ("Baby You Can Chive My Car Burger");
INSERT INTO burgers (burgerName) VALUES ("Babe the Big Blue Cheese Burger");
INSERT INTO burgers (burgerName) VALUES ("Poutine on the Ritz Burger");
INSERT INTO burgers (burgerName) VALUES ("Poblano Picasso Burger");
INSERT INTO burgers (burgerName) VALUES ("Eggers Can't Be Cheesers Burger (with fried egg & cheese)");
INSERT INTO burgers (burgerName) VALUES ("Beets of Burden Burger (served with too many beets)");
INSERT INTO burgers (burgerName) VALUES ("The Human Polenta-pede Burger");
INSERT INTO burgers (burgerName) VALUES ("Chile Relleno-You-Didn't Burger");
INSERT INTO burgers (burgerName) VALUES ("Curd-fect Strangers Burger (comes with cheese curds)");
INSERT INTO burgers (burgerName) VALUES ("Cheeses Is Born Burger (comes with baby Swiss cheese)");
INSERT INTO burgers (burgerName) VALUES ("Paranormal Pepper Jack-tivity Burger (comes with pepper Jack cheese)");
INSERT INTO burgers (burgerName) VALUES ("The Cauliflower's Cumin From Inside the House Burger (comes with cauliflower & cumin)");
INSERT INTO burgers (burgerName) VALUES ("Gourdon-Hamsey Burger (comes with squash & ham)");
INSERT INTO burgers (burgerName) VALUES ("The Silentil Night Burger (comes with lentils)");
INSERT INTO burgers (burgerName) VALUES ("Poutine on the Ritz Burger (comes with poutine fries)");
INSERT INTO burgers (burgerName) VALUES ("Fifth Day of Christmas Burger (comes with five golden rings of onion)");
INSERT INTO burgers (burgerName) VALUES ("Plymouth Roquefort Burger");
INSERT INTO burgers (burgerName) VALUES ("Last of the Mo-jicama (comes with jicama)");
INSERT INTO burgers (burgerName) VALUES ("Cheeses Is Born Burger (comes with baby Swiss cheese)");
INSERT INTO burgers (burgerName) VALUES ("Let's Give 'Em Something Shiitake 'Bout Burger");
INSERT INTO burgers (burgerName) VALUES ("Sgt. Poblano Pepper Lonely Artichoke Hearts Club Burger");
INSERT INTO burgers (burgerName) VALUES ("Jingle Bell Pepper Burger");
INSERT INTO burgers (burgerName) VALUES ("Onion Ring Around the Rosemary");
INSERT INTO burgers (burgerName) VALUES ("I Know Why the Cajun Burger Sings");
INSERT INTO burgers (burgerName) VALUES ("Don't Get Creme Fraiche With Me Burger");
INSERT INTO burgers (burgerName) VALUES ("Open Sesame Burger (served open-faced on a sesame seed bun)");
INSERT INTO burgers (burgerName) VALUES ("Run Gorgonzola Run Burger (made with gorgonzola)");
INSERT INTO burgers (burgerName) VALUES ("It's Fun to Eat at the rYeMCA (comes on rye w/ mustard, cheese & avocado)");
INSERT INTO burgers (burgerName) VALUES ("A Good Manchego Is Hard to Find Burger");
INSERT INTO burgers (burgerName) VALUES ("Chard to a Crisp Burger");
INSERT INTO burgers (burgerName) VALUES ("Chipotle Off the Old Block Burger");
INSERT INTO burgers (burgerName) VALUES ("Blondes Have More Fun-gus Burger (comes with mushrooms)");
INSERT INTO burgers (burgerName) VALUES ("Fig-eta Bout It Burger");
INSERT INTO burgers (burgerName) VALUES ("Never Been Feta (comes with feta cheese)");
INSERT INTO burgers (burgerName) VALUES ("Hummus a Tune Burger");
INSERT INTO burgers (burgerName) VALUES ("Neither Fish Nor Fowl Burger (100% beef)");
INSERT INTO burgers (burgerName) VALUES ("Kale Mary Burger (served with kale)");
INSERT INTO burgers (burgerName) VALUES ("Shoot Out at the Okra Corral Burger");
INSERT INTO burgers (burgerName) VALUES ("Parsnips-Vous Francais Burger");
INSERT INTO burgers (burgerName) VALUES ("Mesclun Around Burger");
INSERT INTO burgers (burgerName) VALUES ("The Life of the Parsley Burger");
INSERT INTO burgers (burgerName) VALUES ("Charbroil Fair Burger (comes with parsley, sage, rosemary, and thyme)");
INSERT INTO burgers (burgerName) VALUES ("Papaya Was a Rolling Stone Burger");
INSERT INTO burgers (burgerName) VALUES ("Kales From the Crypt Burger");
INSERT INTO burgers (burgerName) VALUES ("Two Karat Burger (comes with two carrots)");
INSERT INTO burgers (burgerName) VALUES ("I Fought the Slaw Burger (And the Slaw Won)");
INSERT INTO burgers (burgerName) VALUES ("Parma Parma Parma Chameleon Burger (with Parmesan crisp)");
INSERT INTO burgers (burgerName) VALUES ("Freedom of Choys Burger (comes with bok choy)");
INSERT INTO burgers (burgerName) VALUES ("The Final Kraut Down Burger (comes with sauerkraut)");
INSERT INTO burgers (burgerName) VALUES ("Little Swiss Bunshine (comes on a buttered bun)");
INSERT INTO burgers (burgerName) VALUES ("Texas Chainsaw Massa-curd Burger (comes with cheese curds)");
INSERT INTO burgers (burgerName) VALUES ("She's a Super Leek Burger");
INSERT INTO burgers (burgerName) VALUES ("Bohemian Radishy Burger");
INSERT INTO burgers (burgerName) VALUES ("Cajun Gracefully Burger");
INSERT INTO burgers (burgerName) VALUES ("Krauted House Burger");
INSERT INTO burgers (burgerName) VALUES ("Tarragon in Sixty Seconds Burger");
INSERT INTO burgers (burgerName) VALUES ("If Looks Could Kale Burger");
INSERT INTO burgers (burgerName) VALUES ("Thank God It's Fried Egg Burger");
INSERT INTO burgers (burgerName) VALUES ("The Six Scallion Dollar Man Burger");
INSERT INTO burgers (burgerName) VALUES ("Mushroom With a View Burger (porcini on a double decker)");
INSERT INTO burgers (burgerName) VALUES ("Pickle My Funny Bone Burger");
INSERT INTO burgers (burgerName) VALUES ("Free to Brie You and Me Burger");
INSERT INTO burgers (burgerName) VALUES ("Not If I Can Kelp It Burger");
INSERT INTO burgers (burgerName) VALUES ("The One Yam Band Burger (comes with yams)");
